name: Create Tag

on:
  workflow_run:
    workflows: ["Release (Manually)", "Upgrade httpd Version"]
    types:
      - completed

jobs:
  task:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: homelab-toolchain/.github_shared/.github/workflows/create_tag.yml@main