name: Create Tag

on:
  push:
    branches: ['main']
    paths: ['src/**']

jobs:
  task:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: homelab-toolchain/.github_shared/.github/workflows/create_tag.yml@main